### ISSUE TITLE
Cleaner red circle

### ISSUE THREAD

**Issue by cassidoo** [nadyac/ePatronier#1]
I'm weird about shapes not being perfect.  So I fixed the red circle on the header image. :smile: 

![venmobtn](https://cloud.githubusercontent.com/assets/1454517/5923665/4aa88370-a623-11e4-8529-17deb0e3cd92.PNG)

**Comment by nadyac** [comment]
Ah, that looks so much better. Thanks! I'm replacing the old image with this one :)
